### PR TITLE
fix(app-shell): coerce application env values in AppShellProvider

### LINKED ISSUE #1659: Environment values are not being coerced when using the <ApplicationShellProvider>
**Describe the issue**

When using the `<ApplicationShellProvider>` (mostly for internal usage, you probably ony need the `<ApplicationShell>`), the `environment` prop is not being coerced, when passing it as `environment={window.app}`, causing possible values to be strings (e.g. `"false"`).

**Expected behavior**

The `context.environment` should contain coerced values (e.g. `false` instead of `"false"`) when using only the `<ApplicationShellProvider>`.

### PR DESCRIPTION
**Pull request by emmenko**
Fixes #1659

### CODE REVIEW

File: packages/application-shell/src/components/application-shell-provider/application-shell-provider.tsx [hunk 1]
```diff
@@ -31,47 +32,52 @@ type Props<AdditionalEnvironmentProperties extends {}> = {
...
-            <Router history={ApplicationShellProvider.history}>
-              <GtmBooter trackingEventList={props.trackingEventList || {}}>
-                <Authenticated
-                  render={({ isAuthenticated }) => {
-                    if (isAuthenticated)
-                      return props.children({ isAuthenticated });
+) => {
+  const coercedEnvironmentValues = useCoercedEnvironmentValues<
+    AdditionalEnvironmentProperties
+  >(props.environment);
```
Comment (emmenko) [inline packages/application-shell/src/components/application-shell-provider/application-shell-provider.tsx:38]: I moved this here in the AppShellProvider

File: packages/application-shell/src/components/application-shell/application-shell.tsx [hunk 2]
```diff
@@ -141,9 +144,12 @@ export const RestrictedApplication = <
 >(
   props: Omit<
     Props<AdditionalEnvironmentProperties>,
-    'onRegisterErrorListeners'
+    'environment' | 'onRegisterErrorListeners'
   >
 ) => {
+  const applicationEnvironment = useApplicationContext(
+    (context) => context.environment
+  ) as TApplicationContext<AdditionalEnvironmentProperties>['environment'];
```
Comment (emmenko) [inline packages/application-shell/src/components/application-shell/application-shell.tsx:152]: We can now get the env from the context

File: packages/application-shell/src/components/application-shell/application-shell.tsx [hunk 3]
```diff
@@ -527,30 +529,9 @@ const ApplicationShell = <AdditionalEnvironmentProperties extends {}>(
...
-                          ? {}
-                          : {
-                              // This will be used after being logged in, to redirect to this location.
-                              redirectTo: window.location.origin,
-                            }),
-                      }}
-                    />
-                  )}
-                />
+                <Route path="/logout" component={RedirectToLogout} />
```
Comment (emmenko) [inline packages/application-shell/src/components/application-shell/application-shell.tsx:532]: The "logout redirector" has been moved to a component, so that I can use the hook to get the env from the application context

File: packages/application-shell/src/components/application-shell/redirect-to-logout.tsx [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+import { LOGOUT_REASONS } from '@commercetools-frontend/constants';
+import { useApplicationContext } from '@commercetools-frontend/application-shell-connectors';
+import Redirector from '../redirector';
+
+// When the application redirects to this route, we always force a hard redirect
+// to the logout route of the authentication service.
+const RedirectToLogout = (props: RouteProps) => {
+  const servedByProxy = useApplicationContext(
+    (context) => context.environment.servedByProxy
+  );
```
Comment (emmenko) [inline packages/application-shell/src/components/application-shell/redirect-to-logout.tsx:13]: Get the value from the context
