### PR TITLE
fix(app-shell): to merge internal feature flags with provided ones

### LINKED ISSUE #1146: Custom Applications Menu Icon not showing from other tabs
**Describe the bug**
When you log into MC and access a project with a registered custom application the Icon and Title of the custom app are displayed when on the Welcome page and the Dashboard page. If you navigate to any of the other tabs like products list, orders list etc. you can no longer see the custom application in the menu. 

**To Reproduce**

1. Log into MC and to a project with a registered custom app and observe in the Nav
2. Navigate to the Orders List page 
3. Observe left navigation and that the custom app Icon and title are no longer displayed

**Expected behavior**
Custom App Icon and Title Should be viewable from any other page or tab in the MC. 

**Additional context**
Appears to be reproducible on any project or custom app.

### PR DESCRIPTION
**Pull request by emmenko**
Fixes #1146

### CODE REVIEW

**Comment by tdeekens** [comment]
I propose to approach this differently: we fix it in the apps real quick through the shared flags.

**Comment by tdeekens** [comment]
We can fix this before the release. With the above. 

Either we do this or app-kit exports it's flags and we apply them in the app?

**Comment by emmenko** [comment]
Let's merge the hotfix in the apps first, then release this tomorrow. We still need this for custom apps to properly work as well.

**Comment by tdeekens** [comment]
Added memoization and extractings into a little fn. This looks good to me know.

File: packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.js [hunk 1]
```diff
@@ -61,6 +62,17 @@ export class SetupFlopFlipProvider extends React.PureComponent {
...
+  getFlags = memoize((internalFlags, passedFlags = {}) => ({
+    ...internalFlags,
+    ...passedFlags,
+  }));
+  getDefaultFlags = memoize(
+    (internalDefaultFlags, passedDefaultFlags = {}) => ({
+      ...internalDefaultFlags,
+      ...passedDefaultFlags,
+    })
+  );
```
Comment (tdeekens) [inline packages/application-shell/src/components/setup-flop-flip-provider/setup-flop-flip-provider.js]: Note, to memoize calls are needed as they would bust one another otherwise.
