### PR TITLE
fix(components): style position for `<PortalsContainer>` layout

### LINKED ISSUE #2050: Modal elements overlay causes layout shift if page content has been scrolled
**Describe the issue**

When using the modal components (e.g. dialogs or modal pages), those elements are rendered within a `portals-container` element positioned within the `main` container.

image

If you're on a page (and do not scroll) and you open a modal component, the overlay gets rendered correctly.

However, if the page has some long content and you scroll a bit and then open the modal component, the overlay gets "pushed" up depending on how much you scrolled.

**Expected behavior**

Even if the page scrolls, the overlay should be correctly positioned.

**Screenshots**

image

image

**Additional context**

Ref https://github.com/commercetools/ui-kit/issues/1418

### PR DESCRIPTION
**Pull request by emmenko**
Fixes #2050

### CODE REVIEW

File: packages/application-components/src/components/portals-container/portals-container.tsx [hunk 1]
```diff
@@ -1,18 +1,66 @@
...
-  />
+const PortalsContainer = (props: TPortalsContainerProps) => (
+  <>
+    <Global
+      // Apply some global styles, based on the `.ReactModal__Body--open` class.
+      styles={css`
+        .ReactModal__Body--open
+          ${props.containerSelectorToPreventScrollingOnOpen} {
+          overflow: hidden;
+        }
```
Comment (emmenko) [inline packages/application-components/src/components/portals-container/portals-container.tsx:38]: Moved this here from appkit. It makes sense to keep it co-located with this component.

File: packages/application-components/src/components/portals-container/portals-container.tsx [hunk 2]
```diff
@@ -1,18 +1,66 @@
...
+  /**
+   * The CSS selector to apply the `overflow: hidden` style to (preventing scrolling)
+   * when a modal container is open.
+   */
+  containerSelectorToPreventScrollingOnOpen: string;
+  /**
+   * The `z-index` value to apply to the portal container. Default to `10000`.
+   */
+  zIndex: number;
+};
```
Comment (emmenko) [inline packages/application-components/src/components/portals-container/portals-container.tsx:19]: These optional props allow to adjust things accordingly in case we use modal components outside of a Custom App.

**Review by CarlosCortizasCT — APPROVED** [review]
LGTM
