### PR TITLE
fix(apps-menu): to trigger remote query based on servedByProxy value

### LINKED ISSUE #407: Cannot start application locally in production mode
**Describe the bug**
With #289 we changed how the navigation menu is loaded. For instance, in production the menu configuration is fetched from a `/api/graphql` endpoint on the same domain of the frontend app, as a we have a proxy router between the LB and the applications.

In development though, we usually start the app directly, without the proxy router. To render the menu config of the specific application, we load the menu config from a local file, skipping the graphql request (as the endpoint does not exist).

However, when testing the production build locally like so:

```bash
NODE_ENV=production mc-http-server --csp=$(pwd)/csp.json --config=$(pwd)/env.json --use-local-assets
```

the application starts in "production" mode, triggering the non-existing graphql request.

**Expected behavior**
It should be possible to start the application locally in production mode without having the graphql request to error.

**Additional context**
One solution would be to check for the flag `servedByProxy` from the `env.json`, which usually indicates if the application runs behind the proxy or not.

A bit unrelated to the problem, but we might also want to look into manually putting the menu data into the cache when we don't fetch from the graphql endpoint, so that we can still make the graphql query which will only read from the cache.

### PR DESCRIPTION
**Pull request by emmenko**
Fixes #407

Previously we were basing the logic to load the apps menu config from the local file or remotely based on the `NODE_ENV` variable. However, when testing the production bundle locally in production mode, the app would break because the graphql endpoint does not exist.

Now we base the logic on the `servedByProxy` flag.

Additionally, I also removed the prop `INTERNAL__isApplicationFallback` and assume that the `useFullRedirectsForLinks` comes from the `env.json`. We only use it internally in our fallback app, so I don't consider it a breaking change.

### CODE REVIEW

File: packages/application-shell/src/components/navbar/navbar.js [hunk 1]
```diff
@@ -691,18 +697,22 @@ export default flowRight(
...
+        menuKey: 'navBar',
+      },
+    }),
+  }),
   graphql(FetchProjectExtensionsNavbar, {
     name: 'projectExtensionsQuery',
     skip: ownProps =>
-      !ownProps.areProjectExtensionsEnabled ||
-      process.env.NODE_ENV === 'development',
+      [false, 'false'].includes(ownProps.environment.servedByProxy) ||
```
Comment (adnasa) [inline packages/application-shell/src/components/navbar/navbar.js]: 🙈

**Comment by emmenko** [comment]
> let's test this on a canary build

Even easier 😉

```bash
yarn build
cd playground
yarn build
yarn start:prod:local
```

File: packages/application-shell/src/components/quick-access/quick-access.js [hunk 2]
```diff
@@ -79,7 +79,10 @@ class QuickAccess extends React.Component {
     onChangeProjectDataLocale: PropTypes.func,
     pimSearchProductIds: PropTypes.func.isRequired,
     getPimSearchStatus: PropTypes.func.isRequired,
-    useFullRedirectsForLinks: PropTypes.bool,
+    environment: PropTypes.shape({
+      useFullRedirectsForLinks: PropTypes.oneOf([true, false, 'true', 'false'])
```
Comment (tdeekens) [inline packages/application-shell/src/components/quick-access/quick-access.js]: I guess, like we all, I find this a bit gnarly. Any component relying on this prop will have a quite bloated prop-type eventually. I think it's fine for now but somehow the application context provider (I presume) could also normalise these boolean flags coming in as strings.

File: packages/application-shell/src/components/navbar/navbar.js [hunk 3]
```diff
@@ -691,18 +697,22 @@ export default flowRight(
...
+  withApplicationsMenu({
     queryName: 'applicationsMenuQuery',
-    __DEV_CONFIG__: {
-      menuLoader: ownProps.DEV_ONLY__loadNavbarMenuConfig,
-      menuKey: 'navBar',
-    },
-  })),
+    skipRemoteQuery: ownProps =>
+      [false, 'false'].includes(ownProps.environment.servedByProxy),
+    options: ownProps => ({
```
Comment (tdeekens) [inline packages/application-shell/src/components/navbar/navbar.js]: I like this being an getter now.

File: packages/application-shell/src/components/with-applications-menu/with-applications-menu.js [hunk 4]
```diff
@@ -68,20 +68,17 @@ function withApplicationsMenu(getOptions) {
...
+                  {...this.props}
+                  {...{ [mergedConfig.queryName]: { ...data, error } }}
                 />
               )}
             </Query>
           )}
         />
       );
-    };
-    WrappedComponent.displayName = `withApplicationsMenu(${getDisplayName(
```
Comment (tdeekens) [inline packages/application-shell/src/components/with-applications-menu/with-applications-menu.js]: Ah, this just moved up.

File: packages/application-shell/src/components/quick-access/quick-access.js (hunk 2 above)
Comment (emmenko) [reply packages/application-shell/src/components/quick-access/quick-access.js]: Yeah, but in the app shell we usually don't read from the context. I can coerce the values in the top component though...let me try.

File: packages/application-shell/src/components/with-applications-menu/with-applications-menu.js (hunk 4 above)
Comment (emmenko) [reply packages/application-shell/src/components/with-applications-menu/with-applications-menu.js]: It's now one single component within the HOC, with some if-else.

File: packages/application-shell/src/components/quick-access/quick-access.js (hunk 2 above)
Comment (tdeekens) [reply packages/application-shell/src/components/quick-access/quick-access.js]: Yeah. That's what I meant to suggest. Thanks for trying!

File: packages/application-shell/src/components/application-shell/application-shell.js [hunk 5]
```diff
@@ -335,6 +335,16 @@ RestrictedApplication.propTypes = {
   DEV_ONLY__loadNavbarMenuConfig: PropTypes.func,
 };
 
+const shallowlyCoerceBooleanValues = obj =>
```
Comment (tdeekens) [inline packages/application-shell/src/components/application-shell/application-shell.js]: Nitpick: memoize based on `obj` otherwise the provider will re-render quite a bit.

File: packages/application-shell/src/components/application-shell/application-shell.js [hunk 6]
```diff
@@ -335,6 +335,16 @@ RestrictedApplication.propTypes = {
...
+  Object.keys(obj).reduce((updatedObj, key) => {
+    const value = obj[key];
+    const isBoolean = value === 'true' || value === 'false';
+    return {
+      ...updatedObj,
+      [key]: isBoolean ? value === 'true' : value,
+    };
+  }, {});
```
Comment (tdeekens) [inline packages/application-shell/src/components/application-shell/application-shell.js]: I know this may be a bit over the top but I wanted to suggest it and at least give the full function's code for an easy copy. I just prefer very clear names for things 😄 

```js
const isBooleanAsString = environmentValue =>
  environmentValue === "true" || environmentValue === "false";

const shallowlyCoerceBooleanValues = defaultMemoize(
  uncoercedEnvironmentValues =>
    Object.keys(uncoercedEnvironmentValues).reduce(
      (uncoercedEnvironmentValues, keyOfUncoercedEnvironmentValue) => {
        const uncoercedEnvironmentValue =
          uncoercedEnvironmentValues[keyOfUncoercedEnvironmentValue];

        return {
          ...coercedEnvironmentValues,
          [key]: isBooleanAsString(uncoercedEnvironmentValue)
            ? uncoercedEnvironmentValue === "true"
            : uncoercedEnvironmentValue
        };
      },
      {}
    )
);
```

File: packages/application-shell/src/components/application-shell/application-shell.js [hunk 7]
```diff
@@ -363,17 +373,20 @@ export default class ApplicationShell extends React.Component {
     });
   }
   render() {
+    const environmentValues = shallowlyCoerceBooleanValues(
```
Comment (tdeekens) [inline packages/application-shell/src/components/application-shell/application-shell.js]: `const coercedEnvironmentValues = ...`

**Comment by emmenko** [comment]
@tdeekens thanks for the feedback!

**Comment by tdeekens** [comment]
Thanks for incorporating it!
