### PR TITLE
fix(sdk/middleware): support `apply` endpoint for `orderEdits`

### LINKED ISSUE #2058: applyOrderEditTo applied as a query string parameter
Hi I encountered an issue when using post requests with the frontend sdk.
I am attempting to post and 'apply' OrderEdit but when I apply it I get a malformed url resulting in a 400

```
  return sdkActions.post({
    service: SERVICEPATH.OrdersEdits,
    mcApiProxyTarget: MC_API_PROXY_TARGETS.COMMERCETOOLS_PLATFORM,
    options: { applyOrderEditTo: orderEdit?.id },
    payload: JSON.stringify(applyOrderEdit)
 })
```
Like
orders/edits?/acc7e3ca-afb4-490c-b20c-65910a06ee35/apply

It seems to originate here: https://github.com/commercetools/nodejs/blame/master/packages/api-request-builder/src/create-service.js#L141 where order edit it always false and so its appended as a query string. 

image

I can work around it doing this:
```
 let applyOrderEdit: OrderEditApply = { editVersion: orderEdit?.version, resourceVersion: orderVersion  }
  return sdkActions.post({
    service: SERVICEPATH.OrdersEdits,
    mcApiProxyTarget: MC_API_PROXY_TARGETS.COMMERCETOOLS_PLATFORM,
    options: { id: orderEdit?.id + "/apply" },
    payload: JSON.stringify(applyOrderEdit)
  });
};
```

### PR DESCRIPTION
**Pull request by adnasa**
#### Summary

-  support `apply` endpoint for `orderEdits`
- closes #2058

#### Description

In `sdk/middleware`, we `build()` request [for the respective service](https://github.com/commercetools/nodejs/blob/master/packages/api-request-builder/src/default-services.js#L1:L1) in `sdk`.

It turned out that the `service.build()` is coupled to an option for `orderEdits` that determines whether an `order/edits/${id}/apply` endpoint should be build.

Here is how we reason when building the `order/edits/${id}/apply` endpoint in `sdk/middleware`:

- GIVEN that `service=orderEdits` and `applyOrderEditTo` has a value: [we build the apply endpoint](https://docs.commercetools.com/api/projects/order-edits#apply-an-orderedit)
- GIVEN that `service=orderEdits` and `applyOrderEditTo` has no value: [we build the update endpoint](https://docs.commercetools.com/api/projects/order-edits#update-orderedit-by-id)

### CODE REVIEW

File: packages/sdk/src/middleware/middleware.ts [hunk 1]
```diff
@@ -37,7 +37,17 @@ const actionToUri = (action: TSdkAction, projectKey?: string): string => {
   const service = requestBuilder[action.payload.service];
   if (action.payload.options) service.parse(action.payload.options);
 
-  return service.build();
+  return service.build({
+    // given `service=orderEdits` and given `applyOrderEditTo`, we build an apply endpoint
+    // given `service=orderEdits` and no `applyOrderEditTo`, we build an update endpoint
+    // https://docs.commercetools.com/api/projects/order-edits
+    applyOrderEdit:
+      action.payload.service === 'orderEdits' &&
```
Comment (adnasa) [inline packages/sdk/src/middleware/middleware.ts:45]: This is a bit hacky, but the request-builder doesn't expose any type that I can make use of.

File: packages/sdk/src/middleware/middleware.ts [hunk 2]
```diff
@@ -37,7 +38,16 @@ const actionToUri = (action: TSdkAction, projectKey?: string): string => {
...
   if (action.payload.options) service.parse(action.payload.options);
 
-  return service.build();
+  return service.build({
+    // given `service=orderEdits` and given `applyOrderEditTo`, we build an apply endpoint
+    // given `service=orderEdits` and no `applyOrderEditTo`, we build an update endpoint
+    // https://docs.commercetools.com/api/projects/order-edits
+    applyOrderEdit:
+      action.payload.service === SUPPORTED_SERVICES.orderEdits &&
+      typeof action.payload.options?.applyOrderEditTo === 'string',
```
Comment (adnasa) [inline packages/sdk/src/middleware/middleware.ts:47]: we want to ensure that it is a string, not `null` nor a number

File: packages/sdk/src/middleware/middleware.ts [hunk 3]
```diff
@@ -37,7 +38,16 @@ const actionToUri = (action: TSdkAction, projectKey?: string): string => {
...
-  return service.build();
+  return service.build({
+    // given `service=orderEdits` and given `applyOrderEditTo`, we build an apply endpoint
+    // given `service=orderEdits` and no `applyOrderEditTo`, we build an update endpoint
+    // https://docs.commercetools.com/api/projects/order-edits
+    applyOrderEdit:
+      action.payload.service === SUPPORTED_SERVICES.ORDER_EDITS &&
+      typeof action.payload.options?.applyOrderEditTo === 'string',
+    // at this stage, the `projectKey` should be available already.
+    withProjectKey: true,
```
Comment (qmateub) [inline packages/sdk/src/middleware/middleware.ts:49]: Why it was not there before? 🤔

File: packages/sdk/src/middleware/middleware.ts (hunk 2 above)
Comment (qmateub) [reply packages/sdk/src/middleware/middleware.ts:47]: There is one thing that I'm not sure I follow 100%. Is this parameter then going to be send for all the services and not just for `order-edits` (to `false` obviously) or is this part of the code only related to the interaction with the `order-edits` endpoint?

**Review by qmateub — COMMENTED** [review]
Got what the problem is 👍 . I think I'm maybe missing some context 😅

File: packages/sdk/src/middleware/middleware.ts (hunk 3 above)
Comment (adnasa) [reply packages/sdk/src/middleware/middleware.ts:49]: because it is defaulted https://github.com/commercetools/nodejs/blob/master/packages/api-request-builder/src/create-service.js#L128

I added it here to be more explicit.

File: packages/sdk/src/middleware/middleware.ts (hunk 2 above)
Comment (adnasa) [reply packages/sdk/src/middleware/middleware.ts:47]: This will always be sent to `service.build()`
https://github.com/commercetools/nodejs/blob/master/packages/api-request-builder/src/create-service.js#L128

Which by default is `false`.
We continue sending false as long as it doesn't fulfil the requirements discussed in the PR description

**Review by mohib0306 — APPROVED** [review]
code looks good to me. I was wondering if we need to specify all the supported services now. I see that only one is used and the rest are just defined but not used as of now

File: packages/sdk/src/middleware/middleware.ts [hunk 4]
```diff
@@ -37,7 +38,16 @@ const actionToUri = (action: TSdkAction, projectKey?: string): string => {
...
   if (action.payload.options) service.parse(action.payload.options);
 
-  return service.build();
+  return service.build({
+    // given `service=orderEdits` and given `applyOrderEditTo`, we build an apply endpoint
+    // given `service=orderEdits` and no `applyOrderEditTo`, we build an update endpoint
+    // https://docs.commercetools.com/api/projects/order-edits
+    applyOrderEdit:
+      action.payload.service === SUPPORTED_SERVICES.ORDER_EDITS &&
+      typeof action.payload.options?.applyOrderEditTo === 'string',
```
Comment (tdeekens) [inline packages/sdk/src/middleware/middleware.ts:47]:
```suggestion
    applyOrderEdit: getShouldApplyOrderEdit(action)
```

Somewhere above:

```js
function getShouldApplyOrderEdit(action) {
   return (
      action.payload.service === SUPPORTED_SERVICES.ORDER_EDITS &&
      typeof action.payload.options?.applyOrderEditTo === 'string'
   );
}
```

Generally I wonder what would happen if we demand to pass it in as an option on the payload? So `action.payload.options.applyOrderEditTo`. Would that work or is it against the API?

Comment (adnasa) [reply packages/sdk/src/middleware/middleware.ts:47]: no, we can not really demand it, unless we use unions.
But using unions wouldn't make that the much sense to implement since the consumer can't necessarily be TS

File: packages/sdk/src/constants.ts [hunk 5]
```diff
@@ -0,0 +1,44 @@
+const SUPPORTED_SERVICES = {
```
[the remark this answers is not in the document]
Comment (adnasa) [reply packages/sdk/src/constants.ts:1]: yeah we could.
I want to be verbose that `service` implies an endpoint.

[the remark this answers is not in the document]
Comment (tdeekens) [reply packages/sdk/src/constants.ts:1]: Yup, I can see that just wondering if there is a true benefit in this case. Having this "work-around" isolated might also be nice.

File: packages/sdk/src/middleware/middleware.ts (hunk 4 above)
Comment (tdeekens) [reply packages/sdk/src/middleware/middleware.ts:47]: Got yah. Thanks for clarifying. To combine with my point above. Code looks sharp, tests suberb. I'd subjectively not have the constants and slam the check into a small function.

**Review by qmateub — APPROVED** [review]
🚀

**Comment by adnasa** [comment]
@tdeekens I dropped the services `constants` file and extracted the string into a constant with reference to the original `default-services` in `nodejs`

**Review by tdeekens — APPROVED** [review]
Thanks!

**Comment by adnasa** [comment]
these snapshots emits the following diff.

image

I'm going to take a gamble here and approve them
