### PR TITLE
fix(create-mc-app): escape white spaces in project path

### LINKED ISSUE #1303: Installing a custom app breaks if the folder path contains a white space
**Describe the bug**
When running the script to install the starter template, if one of the folder in the path to the current working directory contains a white space, the command breaks.

**To Reproduce**

1. Assuming the current working directory is:

  ```
  /Users/emmenko/my projects/test
  ```

2. When running the install command

  ```
  npx @commercetools-frontend/create-mc-app \
    my-new-custom-application-project \
    --template starter
  ```

3. The command fail because the template could not be copied

**Expected behavior**
The command should not fail if the path contains whitespaces in the folder names

### PR DESCRIPTION
**Pull request by emmenko**
Fixes #1303

### CODE REVIEW

File: packages/create-mc-app/src/steps/download-template.js [hunk 1]
```diff
@@ -50,13 +51,26 @@ module.exports = function downloadTemplate({
...
-      `Could not copy template "${templateName}" into "${projectDirectoryPath}"`
+      `Could not copy template "${templateName}" into "${sanitizedProjectDirectoryPath}"`
+    );
+  }
+
+  const templatePackageJsonPath = path.join(
+    projectDirectoryPath,
+    'package.json'
+  );
+  if (!fs.existsSync(templatePackageJsonPath)) {
```
Comment (emmenko) [inline packages/create-mc-app/src/steps/download-template.js]: This is just an extra check

File: packages/create-mc-app/src/steps/download-template.js [hunk 2]
```diff
@@ -50,13 +51,26 @@ module.exports = function downloadTemplate({
     tagOrBranchVersion
   );
 
+  const sanitizedProjectDirectoryPath = projectDirectoryPath
+    // Escape white spaces
+    .replace(/ /g, '\\ ');
```
Comment (emmenko) [inline packages/create-mc-app/src/steps/download-template.js]: This is the fix
